name: py38-ITS520-Project
channels:
  - conda-forge
dependencies:
  - python=3.8
  - nbconvert
  - pip=23.2.1=pyhd8ed1ab_0
  - pip:
      - torchvision==0.15.2
      - pandas==2.0.3
      - numpy==1.24.4
      - imageio==2.31.3
      - pillow==10.0.0
      - matplotlib==3.7.2
      - notebook==7.0.6
      - scikit-learn==1.3.0
      - torch==2.0.1 
      - ipympl==0.9.3
      - jupyter==1.0.0
      - opencv-python==4.8.1.78